apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfo
          env:
            - name: PODINFO_UI_PATH
              value: "/podinfo"
