# Middleware to strip the /podinfo prefix
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
spec:
  stripPrefix:
    prefixes:
      - /podinfo

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: podinfo-ingressroute
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/podinfo`)
      kind: Rule
      services:
        - name: podinfo
          port: 9898
      middlewares:
        - name: stripprefix
